image: jetruby/jenkins-ruby
services:
  - postgres

before_script:
  - . /etc/profile.d/rvm.sh
  - rvm --default use 2.2.2
  - bundle install --path /cache

rubocop:
  script:
    - test -f .rubocop.yml && (gem install rubocop --no-ri --no-rdoc && cd app && rubocop) || true
test:
  script:
    - cp config/database.yml.template config/database.yml
    - bundle exec rake db:setup
    - bundle exec rspec
