# Default configuration that all Overcommit configurations inherit from.
#
# This is an opinionated list of which hooks are valuable to run and what their
# out-of-the-box settings should be.

# Where to store hook plugins specific to a repository. These are loaded in
# addition to the default hooks Overcommit comes with. The location is relative
# to the root of the repository.
plugin_directory: '.git-hooks'

# Whether to check if a hook plugin has changed since Overcommit last ran it.
# This is a defense mechanism when working with repositories which can contain
# untrusted code (e.g. when you fetch a pull request from a third party).
# See https://github.com/brigade/overcommit#security for more information.
verify_plugin_signatures: true

# Hooks that are run against every commit message after a user has written it.
# These hooks are useful for enforcing policies on commit messages written for a
# project.
CommitMsg:
  ALL:
    requires_files: false
    quiet: false

  CapitalizedSubject:
    enabled: true
    description: 'Checking subject capitalization'

  EmptyMessage:
    enabled: true
    description: 'Checking for empty commit message'
    quiet: true

  GerritChangeId:
    enabled: false
    description: 'Ensuring Gerrit Change-Id is present'
    required: true

  HardTabs:
    enabled: true
    description: 'Checking for hard tabs'

  RussianNovel:
    enabled: true
    description: 'Checking length of commit message'
    quiet: true

  SingleLineSubject:
    enabled: true
    description: 'Checking subject line'

  SpellCheck:
    enabled: true
    description: 'Checking for misspelled words'
    required_executable: 'hunspell'
    flags: ['-a']

  TextWidth:
    enabled: true
    description: 'Checking text width'
    max_subject_width: 60
    max_body_width: 72

  TrailingPeriod:
    enabled: true
    description: 'Checking for trailing periods in subject'

# Hooks that are run after `git commit` is executed, before the commit message
# editor is displayed. These hooks are ideal for syntax checkers, linters, and
# other checks that you want to run before you allow a commit object to be
# created.
PreCommit:
  ALL:
    problem_on_unmodified_line: warn
    requires_files: true
    required: false
    quiet: false
    exclude: 'vendor/assets/**/*.css'

  AuthorEmail:
    enabled: true
    description: 'Checking author email'
    requires_files: false
    required: true
    quiet: true
    pattern: '^[^@]+@.*$'

  AuthorName:
    enabled: true
    description: 'Checking for author name'
    requires_files: false
    required: true
    quiet: true

  BerksfileCheck:
    enabled: true
    description: 'Checking Berksfile lock'
    required_executable: 'berks'
    flags: ['list', '--quiet']
    install_command: 'gem install berks'
    include:
      - 'Berksfile'
      - 'Berksfile.lock'

  Brakeman:
    enabled: true
    description: 'Checking for security vulnerabilities'
    required_executable: 'brakeman'
    flags: ['--exit-on-warn', '--quiet', '--summary', '--only-files']
    install_command: 'gem install brakeman'
    include:
      - '**/*.rb'

  BrokenSymlinks:
    enabled: true
    description: 'Checking for broken symlinks'
    quiet: true

  BundleCheck:
    enabled: false
    description: 'Checking Gemfile dependencies'
    required_executable: 'bundle'
    flags: ['check']
    install_command: 'gem install bundler'
    include:
      - 'Gemfile'
      - 'Gemfile.lock'
      - '*.gemspec'

  CaseConflicts:
    enabled: true
    description: 'Checking for case-insensitivity conflicts'
    quiet: true

  ChamberSecurity:
    enabled: false
    description: 'Checking that settings have been secured with Chamber'
    required_executable: 'chamber'
    flags: ['secure', '--files']
    install_command: 'gem install chamber'
    include:
      - 'config/settings.yml'
      - 'config/settings/**/*.yml'

  CoffeeLint:
    enabled: true
    description: 'Analyzing with coffeelint'
    required_executable: 'coffeelint'
    required_library: 'json'
    flags: ['--reporter=raw']
    install_command: 'npm install -g coffeelint'
    include: '**/*.coffee'

  CssLint:
    enabled: enabled
    description: 'Analyzing with csslint'
    required_executable: 'csslint'
    flags: ['--quiet', '--format=compact']
    install_command: 'npm install -g csslint'
    include: '**/*.css'

  EsLint:
    enabled: true
    description: 'Analyzing with ESLint'
    required_executable: 'eslint'
    flags: ['--format=compact']
    install_command: 'npm install -g eslint'
    include: '**/*.js'

  GoLint:
    enabled: false
    description: 'Analyzing with golint'
    required_executable: 'golint'
    install_command: 'go get github.com/golang/lint/golint'
    include: '**/*.go'

  GoVet:
    enabled: false
    description: 'Analyzing with go vet'
    required_executable: 'go'
    flags: ['tool', 'vet']
    install_command: 'go get golang.org/x/tools/cmd/vet'
    include: '**/*.go'

  HamlLint:
    enabled: true
    description: 'Analyzing with haml-lint'
    required_executable: 'haml-lint'
    install_command: 'gem install haml-lint'
    include: '**/*.haml'

  HardTabs:
    enabled: true
    description: 'Checking for hard tabs'
    quiet: true
    required_executable: 'grep'
    flags: ['-IHn', "\t"]
    exclude: '**/*.svg'

  HtmlTidy:
    enabled: true
    description: 'Analyzing HTML with tidy'
    required_executable: 'tidy'
    flags: ['-errors', '-quiet', '-utf8']
    include: '**/*.html'

  ImageOptim:
    enabled: false
    description: 'Checking for optimizable images'
    required_executable: 'image_optim'
    install_command: 'gem install image_optim'
    include:
      - '**/*.gif'
      - '**/*.jpeg'
      - '**/*.jpg'
      - '**/*.png'
      - '**/*.svg'

  JavaCheckstyle:
    enabled: false
    description: 'Analyzing with checkstyle'
    required_executable: 'checkstyle'
    flags: ['-c', '/sun_checks.xml']
    include: '**/*.java'

  Jscs:
    enabled: false
    description: 'Analyzing with JSCS'
    required_executable: 'jscs'
    flags: ['--reporter=inline', '--verbose']
    install_command: 'npm install -g jscs'
    include: '**/*.js'

  JsHint:
    enabled: true
    description: 'Analyzing with JSHint'
    required_executable: 'jshint'
    flags: ['--verbose']
    install_command: 'npm install -g jshint'
    include: '**/*.js'

  JsLint:
    enabled: true
    description: 'Analyzing with JSLint'
    required_executable: 'jslint'
    flags: ['--terse']
    install_command: 'npm install -g jslint'
    include: '**/*.js'

  Jsl:
    enabled: false
    description: 'Analyzing with JSL'
    required_executable: 'jsl'
    flags: ['-nologo', '-nofilelisting', '-nocontext', '-nosummary']
    include: '**/*.js'

  JsonSyntax:
    enabled: true
    description: 'Validating JSON syntax'
    required_library: 'json'
    install_command: 'gem install json'
    include: '**/*.json'

  LocalPathsInGemfile:
    enabled: true
    description: 'Checking for local paths in Gemfile'
    required_executable: 'grep'
    flags: ['-IHnE', "^[^#]*((\\bpath:)|(:path[ \t]*=>))"]
    include: '**/Gemfile'

  MergeConflicts:
    enabled: true
    description: 'Checking for merge conflicts'
    quiet: true
    required_executable: 'grep'
    flags: ['-IHn', "^<<<<<<<[ \t]"]

  Pep257:
    enabled: false
    description: 'Analyzing docstrings with pep257'
    required_executable: 'pep257'
    install_command: 'pip install pep257'
    include: '**/*.py'

  Pep8:
    enabled: false
    description: 'Analyzing with pep8'
    required_executable: 'pep8'
    install_command: 'pip install pep8'
    include: '**/*.py'

  Pyflakes:
    enabled: false
    description: 'Analyzing with pyflakes'
    required_executable: 'pyflakes'
    install_command: 'pip install pyflakes'
    include: '**/*.py'

  Pylint:
    enabled: false
    description: 'Analyzing with Pylint'
    required_executable: 'pylint'
    install_command: 'pip install pylint'
    flags:
      - '--msg-template="{path}:{line}:{C}: {msg} ({symbol})"'
      - '--reports=n'
      - '--persistent=n'
    include: '**/*.py'

  PythonFlake8:
    enabled: false
    description: 'Analyzing with flake8'
    required_executable: 'flake8'
    install_command: 'pip install flake8'
    include: '**/*.py'

  RailsSchemaUpToDate:
    enabled: true
    description: 'Checking if database schema is up to date'
    include:
      - 'db/migrate/*.rb'
      - 'db/schema.rb'
      - 'db/structure.sql'

  Reek:
    enabled: true
    description: 'Analyzing with Reek'
    required_executable: 'reek'
    flags: ['--single-line', '--no-color']
    install_command: 'gem install reek'
    include:
      - '**/*.gemspec'
      - '**/*.rake'
      - '**/*.rb'
      - '**/Gemfile'
      - '**/Rakefile'

  RuboCop:
    enabled: true
    description: 'Analyzing with RuboCop'
    required_executable: 'rubocop'
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names']
    install_command: 'gem install rubocop'
    include:
      - '**/*.gemspec'
      - '**/*.rake'
      - '**/*.rb'
      - '**/Gemfile'
      - '**/Rakefile'

  RubyLint:
    enabled: true
    description: 'Analyzing with ruby-lint'
    required_executable: 'ruby-lint'
    flags: ['--presenter=syntastic', '--levels=error,warning']
    install_command: 'gem install ruby-lint'
    include:
      - '**/*.gemspec'
      - '**/*.rb'

  Scalariform:
    enabled: false
    description: 'Checking formatting with Scalariform'
    required_executable: 'scalariform'
    flags: ['--test']
    include: '**/*.scala'

  Scalastyle:
    enabled: false
    description: 'Analyzing with Scalastyle'
    required_executable: 'scalastyle'
    include: '**/*.scala'

  ScssLint:
    enabled: true
    description: 'Analyzing with scss-lint'
    required_executable: 'scss-lint'
    install_command: 'gem install scss-lint'
    include: '**/*.scss'

  SemiStandard:
    enabled: true
    description: 'Analyzing with semistandard'
    required_executable: 'semistandard'
    flags: ['--verbose']
    install_command: 'npm install -g semistandard'
    include: '**/*.js'

  ShellCheck:
    enabled: true
    description: 'Analyzing with ShellCheck'
    required_executable: 'shellcheck'
    flags: ['--format=gcc']
    include: '**/*.sh'

  SlimLint:
    enabled: false
    description: 'Analyzing with slim-lint'
    required_executable: 'slim-lint'
    install_command: 'gem install slim_lint'
    include: '**/*.slim'

  Standard:
    enabled: true
    description: 'Analyzing with standard'
    required_executable: 'standard'
    flags: ['--verbose']
    install_command: 'npm install -g standard'
    include: '**/*.js'

  TrailingWhitespace:
    enabled: true
    description: 'Checking for trailing whitespace'
    required_executable: 'grep'
    flags: ['-IHn', "[ \t]$"]

  TravisLint:
    enabled: false
    description: 'Checking Travis CI configuration'
    required_executable: 'travis'
    flags: ['lint']
    install_command: 'gem install travis'
    include: '.travis.yml'

  Vint:
    enabled: false
    description: 'Analyzing with Vint'
    required_executable: 'vint'
    install_command: 'pip install vim-vint'
    include:
      - '**/*.vim'
      - '**/*.vimrc'

  W3cCss:
    enabled: true
    description: 'Analyzing with W3C CSS validation service'
    required_library: 'w3c_validators'
    install_command: 'gem install w3c_validators'
    validator_uri: 'http://jigsaw.w3.org/css-validator/validator'
    language: 'en'
    profile: 'css3'
    warn_level: 2
    include:
      - '**/*.css'

  W3cHtml:
    enabled: true
    description: 'Analyzing with W3C HTML validation service'
    required_library: 'w3c_validators'
    install_command: 'gem install w3c_validators'
    validator_uri: 'http://validator.w3.org/check'
    charset: 'utf-8'
    doctype: 'HTML5'
    include:
      - '**/*.html'

  XmlLint:
    enabled: true
    description: 'Analyzing with xmllint'
    required_executable: 'xmllint'
    flags: ['--noout']
    include:
      - '**/*.xml'
      - '**/*.svg'

  XmlSyntax:
    enabled: true
    description: 'Checking XML syntax'
    required_library: 'rexml/document'
    include:
      - '**/*.xml'
      - '**/*.svg'

  YamlSyntax:
    enabled: true
    description: 'Checking YAML syntax'
    required_library: 'yaml'
    include:
      - '**/*.yaml'
      - '**/*.yml'

# Hooks that run after HEAD changes or a file is explicitly checked out.
PostCheckout:
  ALL:
    required: false
    quiet: false

  IndexTags:
    enabled: true
    description: 'Generating tags file from source'
    quiet: true
    required_executable: 'ctags'

  SubmoduleStatus:
    enabled: true
    description: 'Checking submodule status'
    quiet: true
    recursive: false

# Hooks that run after a commit is created.
PostCommit:
  ALL:
    requires_files: false
    required: false
    quiet: false

  GitGuilt:
    enabled: true
    description: 'Calculating changes in blame since last commit'
    requires_files: true
    required_executable: 'git-guilt'
    flags: ['HEAD~', 'HEAD']
    install_command: 'npm install -g git-guilt'

  IndexTags:
    enabled: true
    description: 'Generating tags file from source'
    quiet: true
    required_executable: 'ctags'

  SubmoduleStatus:
    enabled: true
    description: 'Checking submodule status'
    quiet: true
    recursive: false

# Hooks that run after `git merge` executes successfully (no merge conflicts).
PostMerge:
  ALL:
    requires_files: false
    quiet: false

  IndexTags:
    enabled: true
    description: 'Generating tags file from source'
    quiet: true
    required_executable: 'ctags'

  SubmoduleStatus:
    enabled: true
    description: 'Checking submodule status'
    quiet: true
    recursive: false

# Hooks that run after a commit is modified by an amend or rebase.
PostRewrite:
  ALL:
    requires_files: false
    quiet: false

  IndexTags:
    enabled: true
    description: 'Generating tags file from source'
    quiet: true
    required_executable: 'ctags'

  SubmoduleStatus:
    enabled: true
    description: 'Checking submodule status'
    quiet: true
    recursive: false

# Hooks that run during `git push`, after remote refs have been updated but
# before any objects have been transferred.
PrePush:
  ALL:
    requires_files: false
    required: false
    quiet: false

  ProtectedBranches:
    enabled: true
    description: 'Checking for illegal pushes to protected branches'
    branches: ['master']

  RSpec:
    enabled: true
    description: 'Running RSpec test suite'
    required_executable: 'rspec'

# Hooks that run during `git rebase`, before any commits are rebased.
# If a hook fails, the rebase is aborted.
PreRebase:
  ALL:
    requires_files: false
    required: false
    quiet: false

  MergedCommits:
    enabled: true
    description: 'Checking for commits that have already been merged'
    branches: ['master']
