tracker_project_id: 1393994

jira_login:         admin
jira_host:          https://astaro.atlassian.net
jira_uri_scheme:    https
jira_port:          80
jira_project:       TES
jira_filter:        10800

retry_count:        5

script_first_start: 5
script_repeat_time: '5m'

notification_first_start: 0
notification_repeat_time: '1m'

jira_custom_fields:
  pivotal_points:   'Story Points'
  pivotal_url:      'Pivotal Tracker URL'

jira_issue_types:
  bug: 1
  feature: 2
  chore: 9

emails:
  - example1@mail.mm
  - example2@mail.mm
