development: &development
  adapter: postgresql
  encoding: unicode
  database: j2p_development
  pool: 100
  username: ruby
  password: 123321
  host: localhost
  min_messages: WARNING

test:
  <<: *development
  database: j2p_test

production:
  <<: *development
  database: j2p_production
